name: .NET Core

on:
  push:
    branches: [ kafka-lens ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1      
      with:
        dotnet-version: 3.1.301
    #- name: LS
    #  run: ls -R
    #- name: Install dependencies
    #  run: dotnet restore
    #  working-directory:  cSharp/Kafka.Lens
      
    - name: Build
      run: dotnet build Kafka.Lens/Kafka.Lens.sln --configuration Release
    - name: Test
      run: dotnet test Kafka.Lens/Kafka.Lens.sln --no-restore --verbosity normal