name: .NET Core

on:
  push:
    branches: [ kafka-lens ]
  pull_request:
    branches: [ kafka-lens ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: LS
      run: ls
    - name: Install dependencies
      run: dotnet restore cSharp/Kafka.Lens/Kafka.Lens.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
